### ISSUE TITLE
Bind to VehicleManager in onResume(), unbind in onPause() in the sample code

### ISSUE THREAD

**Issue by tgiuli** [openxc/openxcplatform.com#27] opened 2013-09-19 17:34 UTC
See openxc/openxc-starter#1

Fixed by commit 5491cf..53880e5

**Comment by peplin** [comment] 2013-09-24 16:17
@mjohn706 can you make that same change from the starter project in the website's example? There's a gist at the bottom with the complete example, but since we have that starter project now, could you just link to it instead?

**Comment by mjohn706** [comment] 2013-09-24 18:37
@Chris if you are referring specifically to http://openxcplatform.com/getting-started/tutorial.html, it needs more rewrite than that: it says, for example, "Add a ServiceConnection to your activity", but then the "..." covers up the code that might have told the reader WHERE in the Activity to add it. Should it be in onStart? onCreate? onResume?

Or are you proposing replacing all of this link, or all of the "complete example" at the bottom with a link to the new code in openxc-starter?

**Comment by peplin** [comment] 2013-09-24 20:46
Whatever rewrite is necessary is fine, the text should be consistent with the in-line example code and also with the starter project. The ServiceConnection doesn't go inside any method, though, so I think that's still correct.

To your last question, I'm just proposing replacing the "complete exmaple" at the bottom with a link to the starter project, not the entire page.

**Comment by mjohn706** [comment] 2013-09-24 22:20
OK, I did the rewrite. And made the getting-started/tutorial match the new example, binding in onStart() instead of onCreate etc. as in openxc-starter#1.

**Comment by mjohn706** [comment] 2013-09-24 22:43
Hi, Chris-

As you can see from the updates to the ticket, I did this. But after my final update to it (though I have not closed it yet), I realized: I changed all the scattered snippets, but I am not sure how to access the code your Javascript displays: recall you used <script src="https://gist.github.com/peplin/5464835.js"></script> to do the final display of the completed code.

I already pushed the changes to the openxcplatorm repository. So people viewing it now will notice the discrepancy, but I think this is more annoying than fatal now, since it still gives the link to the starter application that has it correct.

On Sep 24, 2013, at 1:46 PM, Christopher Peplin <notifications@github.com<mailto:notifications@github.com>>
 wrote:

Whatever rewrite is necessary is fine, the text should be consistent with the in-line example code and also with the starter project. The ServiceConnection doesn't go inside any method, though, so I think that's still correct.

To your last question, I'm just proposing replacing the "complete exmaple" at the bottom with a link to the starter project, not the entire page.

**Comment by peplin** [comment] 2013-09-25 02:12
You can just remove the embedded Gist in favor of the start project repo, that's fine. Thanks, Matthew! 

One question about the updated example and rewording - does it need to bindService in both onStart and onResume? Wouldn't having it just be in onResume take care of it?

**Comment by mjohn706** [comment] 2013-09-25 17:25
Hi, Chris-

How interesting you should ask! I anguished over that for a bit, since it has a strong appearance of redundancy. But  not one of the code samples I was following did it this way. Nor did they explain fully why they did things the way they did. My guess is that they covered both onStart and onResume because they wanted to remove that small delay that results from waiting for onResume in the most common case, which is that onStart is called first and then a bit later, onResume.

I will go ahead and follow your suggestion of removing the embedded Gist and leaving only the mention of the start project repo. So then should I close the issue myself, or leave that up to the originator?

On Sep 24, 2013, at 7:12 PM, Christopher Peplin <notifications@github.com<mailto:notifications@github.com>> wrote:

You can just remove the embedded Gist in favor of the start project repo, that's fine. Thanks, Matthew!

One question about the updated example and rewording - does it need to bindService in both onStart and onResume? Wouldn't having it just be in onResume take care of it?

**Comment by peplin** [comment] 2013-09-25 17:50
Close at your leisure!

**Comment by peplin** [comment] 2013-10-09 16:52
OK I just confirmed this is resolved and I'll close it.

**Closed as completed by peplin** 2013-10-09 16:52 UTC
